// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAW9d-LXdpwfYb8PBOe7DFEtjFPXT2Onts',
    appId: '1:574707989838:web:e7a656e081ef2bba14f21f',
    messagingSenderId: '574707989838',
    projectId: 'flutterfirebasetutorial-85a48',
    authDomain: 'flutterfirebasetutorial-85a48.firebaseapp.com',
    storageBucket: 'flutterfirebasetutorial-85a48.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWRwN3iBgJtbsd3z3WhDh25BOQ5E5SYQ8',
    appId: '1:574707989838:android:2810adbeef834f2014f21f',
    messagingSenderId: '574707989838',
    projectId: 'flutterfirebasetutorial-85a48',
    storageBucket: 'flutterfirebasetutorial-85a48.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfDvQDeXRryQ_nFFwK3XsbJPIuzQhoj_U',
    appId: '1:574707989838:ios:9ab3b641d0bfd89914f21f',
    messagingSenderId: '574707989838',
    projectId: 'flutterfirebasetutorial-85a48',
    storageBucket: 'flutterfirebasetutorial-85a48.firebasestorage.app',
    iosBundleId: 'com.example.jurustayGroup14',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfDvQDeXRryQ_nFFwK3XsbJPIuzQhoj_U',
    appId: '1:574707989838:ios:9ab3b641d0bfd89914f21f',
    messagingSenderId: '574707989838',
    projectId: 'flutterfirebasetutorial-85a48',
    storageBucket: 'flutterfirebasetutorial-85a48.firebasestorage.app',
    iosBundleId: 'com.example.jurustayGroup14',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAW9d-LXdpwfYb8PBOe7DFEtjFPXT2Onts',
    appId: '1:574707989838:web:eafac83b1370fbbf14f21f',
    messagingSenderId: '574707989838',
    projectId: 'flutterfirebasetutorial-85a48',
    authDomain: 'flutterfirebasetutorial-85a48.firebaseapp.com',
    storageBucket: 'flutterfirebasetutorial-85a48.firebasestorage.app',
  );

}